# Generated by Django 5.1.1 on 2025-06-20 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='activities/photos/', verbose_name='صورة النشاط')),
                ('description', models.TextField(verbose_name='وصف النشاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='materialaidrequest',
            name='beneficiary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_aids', to='myappG.beneficiary', verbose_name='المستفيد'),
        ),
        migrations.AlterField(
            model_name='medicalaidrequest',
            name='aid_type',
            field=models.CharField(choices=[('nebulizer', 'جهاز رذاذ'), ('diabetes_device', 'جهاز سكري'), ('pressure_device', 'جهاز ضغط'), ('walker', 'جهاز مشي'), ('wheelchair', 'كرسي متحرك'), ('medical_mattress', 'إسفنجة طبية')], max_length=50, verbose_name='نوع المساعدة الطبية'),
        ),
        migrations.AlterField(
            model_name='medicalaidrequest',
            name='beneficiary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_aids', to='myappG.beneficiary', verbose_name='المستفيد'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='beneficiary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myappG.beneficiary', verbose_name='المستفيد'),
        ),
    ]
