# Generated by Django 5.1.1 on 2025-06-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0002_activity_alter_materialaidrequest_beneficiary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='news/photos/', verbose_name='صورة الخبر')),
                ('description', models.TextField(verbose_name='تفاصيل الخبر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-created_at'],
            },
        ),
    ]
