# Generated by Django 5.1.1 on 2025-06-22 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب مشروع', 'verbose_name_plural': 'طلبات المشاريع'},
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='estimated_budget',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default=None, max_length=10, verbose_name='الجنس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone_number',
            field=models.EmailField(default=None, max_length=254, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalaidrequest',
            name='medical_report',
            field=models.ImageField(default=None, upload_to='medical_reports/', verbose_name='صورة التقرير الطبي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='area',
            field=models.CharField(default=None, max_length=100, verbose_name='المساحة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإضافة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='experience',
            field=models.TextField(default=None, verbose_name='الخبرة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='ownership',
            field=models.CharField(default=None, max_length=100, verbose_name='الملكية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='tools',
            field=models.TextField(default=None, verbose_name='الأدوات المتوفرة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='living_status',
            field=models.CharField(choices=[('owned', 'ملك'), ('rented', 'استئجار'), ('hosted', 'استضافة'), ('shelter_center', 'مركز إيواء اجتماعي'), ('camp', 'مخيم'), ('other', 'غير ذلك')], max_length=50, verbose_name='طبيعة الإقامة'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل'), ('husband_missing', 'الزوج مفقود')], max_length=50, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='residence_type',
            field=models.CharField(choices=[('hosted', 'مستضاف'), ('returnee', 'عائد'), ('refugee', 'لاجئ'), ('idp', 'نازح داخلي'), ('affected_community', 'أفراد مجتمع متضرر'), ('other', 'غير ذلك')], max_length=50, verbose_name='الخلفية الشخصية'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='project_type',
            field=models.CharField(choices=[('commercial', 'مشروع تجاري'), ('agricultural', 'مشروع زراعي')], max_length=50, verbose_name='نوع المشروع'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('under_review', 'قيد التقييم'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
