# Generated by Django 5.1.1 on 2025-06-22 22:31

import django.core.validators
import myappG.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0004_alter_projectrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='family_members',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)], verbose_name='عدد أفراد الأسرة'),
        ),
        migrations.AlterField(
            model_name='materialaidrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('delivered', 'تم التسليم')], default='pending', max_length=50, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='medicalaidrequest',
            name='medical_report',
            field=models.FileField(upload_to='medical_reports/', validators=[myappG.models.MedicalAidRequest.validate_medical_report_file], verbose_name='صورة أو ملف التقرير الطبي'),
        ),
        migrations.AlterField(
            model_name='medicalaidrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('delivered', 'تم التسليم')], default='pending', max_length=50, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
