# Generated by Django 5.1.1 on 2025-06-23 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0005_alter_beneficiary_family_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_request', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن المراجعة'),
        ),
    ]
