# Generated by Django 5.1.1 on 2025-06-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0006_projectrequest_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='activities/photos/', verbose_name='صورة النشاط'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/photos/', verbose_name='صورة الخبر'),
        ),
    ]
