# Generated by Django 5.1.1 on 2025-06-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0007_alter_activity_photo_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'مسؤول الجمعية'), ('staff', 'موظف الجمعية'), ('field_team', 'فريق الميدان'), ('beneficiary', 'مستفيد')], max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
