# Generated by Django 5.1.1 on 2025-06-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalaidrequest',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تاريخ التسليم'),
        ),
    ]
