# Generated by Django 5.1.1 on 2025-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0010_alter_materialaidrequest_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تاريخ التسليم'),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
    ]
