# Generated by Django 5.1.1 on 2025-06-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0011_projectrequest_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialaidrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'طلب مساعدة عينية', 'verbose_name_plural': 'طلبات المساعدات العينية'},
        ),
        migrations.AlterModelOptions(
            name='medicalaidrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'طلب مساعدة طبية', 'verbose_name_plural': 'طلبات المساعدات الطبية'},
        ),
        migrations.AlterModelOptions(
            name='projectrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'طلب مشروع', 'verbose_name_plural': 'طلبات المشاريع'},
        ),
        migrations.RemoveConstraint(
            model_name='materialaidrequest',
            name='unique_material_aid_per_beneficiary',
        ),
        migrations.RemoveConstraint(
            model_name='medicalaidrequest',
            name='unique_medical_aid_per_beneficiary',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=None, verbose_name='تاريخ الطلب'),
            preserve_default=False,
        ),
    ]
