# Generated by Django 5.1.1 on 2025-06-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0012_alter_materialaidrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب مشروع', 'verbose_name_plural': 'طلبات المشاريع'},
        ),
        migrations.RenameField(
            model_name='projectrequest',
            old_name='request_date',
            new_name='created_at',
        ),
    ]
