# Generated by Django 5.1.1 on 2025-06-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0013_alter_projectrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'طلب مشروع', 'verbose_name_plural': 'طلبات المشاريع'},
        ),
        migrations.RenameField(
            model_name='projectrequest',
            old_name='created_at',
            new_name='request_date',
        ),
    ]
