# Generated by Django 5.1.1 on 2025-06-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0014_alter_projectrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
