# Generated by Django 5.1.1 on 2025-07-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappG', '0017_pendinguser_customuser_address_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
