from .Medical import *
from .User import *
from .Material import *
from .Project import *
from .Statistics import *
from .Activity import *
from .News import *
from .List_all_requests import *
from .Feedback import *
from .serve import *